name: CI (lint)

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: "3.12" }
      - run: python -m pip install --upgrade pip
      - run: pip install ruff mypy types-requests types-urllib3
      - run: ruff check .
      - run: mypy --ignore-missing-imports app.py fetch_all_mirrors.py
